"""Định nghĩa chỉ tiêu BCTC SME (B01-DN / B02-DN) — map từ bctc_line_code trên COA."""
from __future__ import annotations

# kind:
#   header  — nhóm, không số
#   leaf    — cộng từ tài khoản có bctc_line_code = code (hoặc coa_line)
#   calc    — công thức từ chỉ tiêu khác
# sign_role (leaf):
#   asset / liability / equity / contra_asset / revenue / expense

B01_BALANCE_SHEET: list[dict] = [
    {'code': 'A', 'name': 'A. TÀI SẢN NGẮN HẠN', 'kind': 'header', 'level': 0},
    {'code': '110', 'name': 'I. Tiền và các khoản tương đương tiền', 'kind': 'calc', 'level': 1,
     'formula': '111'},
    {'code': '111', 'name': '1. Tiền', 'kind': 'leaf', 'level': 2, 'sign_role': 'asset'},
    {'code': '120', 'name': 'II. Đầu tư tài chính ngắn hạn', 'kind': 'calc', 'level': 1,
     'formula': '121 + 123'},
    {'code': '121', 'name': '1. Chứng khoán kinh doanh', 'kind': 'leaf', 'level': 2, 'sign_role': 'asset',
     'coa_line': '120'},  # COA seed dùng bctc=120
    {'code': '123', 'name': '2. Đầu tư nắm giữ đến ngày đáo hạn', 'kind': 'leaf', 'level': 2, 'sign_role': 'asset'},
    {'code': '130', 'name': 'III. Các khoản phải thu ngắn hạn', 'kind': 'calc', 'level': 1,
     'formula': '131 + 132 + 133 + 136 - 137'},
    {'code': '131', 'name': '1. Phải thu ngắn hạn của khách hàng', 'kind': 'leaf', 'level': 2, 'sign_role': 'asset'},
    {'code': '132', 'name': '2. Phải thu nội bộ ngắn hạn', 'kind': 'leaf', 'level': 2, 'sign_role': 'asset'},
    {'code': '133', 'name': '3. Thuế GTGT được khấu trừ', 'kind': 'leaf', 'level': 2, 'sign_role': 'asset'},
    {'code': '136', 'name': '4. Phải thu ngắn hạn khác', 'kind': 'leaf', 'level': 2, 'sign_role': 'asset'},
    {'code': '137', 'name': '5. Dự phòng phải thu khó đòi (*)', 'kind': 'leaf', 'level': 2, 'sign_role': 'contra_asset'},
    {'code': '140', 'name': 'IV. Hàng tồn kho', 'kind': 'calc', 'level': 1, 'formula': '141'},
    {'code': '141', 'name': '1. Hàng tồn kho', 'kind': 'leaf', 'level': 2, 'sign_role': 'asset'},
    {'code': '150', 'name': 'V. Tài sản ngắn hạn khác', 'kind': 'calc', 'level': 1, 'formula': '155'},
    {'code': '155', 'name': '1. Tài sản ngắn hạn khác', 'kind': 'leaf', 'level': 2, 'sign_role': 'asset'},
    {'code': '100', 'name': 'TỔNG CỘNG TÀI SẢN NGẮN HẠN', 'kind': 'calc', 'level': 0,
     'formula': '110 + 120 + 130 + 140 + 150', 'bold': True},

    {'code': 'B', 'name': 'B. TÀI SẢN DÀI HẠN', 'kind': 'header', 'level': 0},
    {'code': '221', 'name': '1. TSCĐ hữu hình / thuê TC (nguyên giá)', 'kind': 'leaf', 'level': 2, 'sign_role': 'asset'},
    {'code': '223', 'name': '2. Hao mòn lũy kế TSCĐ (*)', 'kind': 'leaf', 'level': 2, 'sign_role': 'contra_asset'},
    {'code': '222', 'name': '3. TSCĐ hữu hình (giá trị còn lại)', 'kind': 'calc', 'level': 2,
     'formula': '221 - 223'},
    {'code': '227', 'name': '4. TSCĐ vô hình (còn lại)', 'kind': 'leaf', 'level': 2, 'sign_role': 'asset'},
    {'code': '230', 'name': '5. Bất động sản đầu tư', 'kind': 'leaf', 'level': 2, 'sign_role': 'asset'},
    {'code': '220', 'name': 'I. Tài sản cố định', 'kind': 'calc', 'level': 1,
     'formula': '222 + 227 + 230'},
    {'code': '242', 'name': '1. Chi phí XDCB dở dang / trả trước dài hạn', 'kind': 'leaf', 'level': 2, 'sign_role': 'asset'},
    {'code': '240', 'name': 'II. Tài sản dở dang dài hạn', 'kind': 'calc', 'level': 1, 'formula': '242'},
    {'code': '251', 'name': '1. Đầu tư vào công ty con', 'kind': 'leaf', 'level': 2, 'sign_role': 'asset'},
    {'code': '252', 'name': '2. Đầu tư vào công ty liên doanh, liên kết', 'kind': 'leaf', 'level': 2, 'sign_role': 'asset'},
    {'code': '253', 'name': '3. Đầu tư dài hạn khác', 'kind': 'leaf', 'level': 2, 'sign_role': 'asset'},
    {'code': '250', 'name': 'III. Đầu tư tài chính dài hạn', 'kind': 'calc', 'level': 1,
     'formula': '251 + 252 + 253'},
    {'code': '262', 'name': '1. Tài sản thuế thu nhập hoãn lại', 'kind': 'leaf', 'level': 2, 'sign_role': 'asset'},
    {'code': '260', 'name': 'IV. Tài sản dài hạn khác', 'kind': 'calc', 'level': 1, 'formula': '262'},
    {'code': '200', 'name': 'TỔNG CỘNG TÀI SẢN DÀI HẠN', 'kind': 'calc', 'level': 0,
     'formula': '220 + 240 + 250 + 260', 'bold': True},
    {'code': '270', 'name': 'TỔNG CỘNG TÀI SẢN', 'kind': 'calc', 'level': 0,
     'formula': '100 + 200', 'bold': True, 'highlight': True},

    {'code': 'C', 'name': 'C. NỢ PHẢI TRẢ', 'kind': 'header', 'level': 0},
    {'code': '311', 'name': '1. Phải trả người bán ngắn hạn', 'kind': 'leaf', 'level': 2, 'sign_role': 'liability'},
    {'code': '313', 'name': '2. Thuế và các khoản phải nộp Nhà nước', 'kind': 'leaf', 'level': 2, 'sign_role': 'liability'},
    {'code': '314', 'name': '3. Phải trả người lao động', 'kind': 'leaf', 'level': 2, 'sign_role': 'liability'},
    {'code': '315', 'name': '4. Chi phí phải trả ngắn hạn', 'kind': 'leaf', 'level': 2, 'sign_role': 'liability'},
    {'code': '316', 'name': '5. Phải trả nội bộ ngắn hạn', 'kind': 'leaf', 'level': 2, 'sign_role': 'liability'},
    {'code': '318', 'name': '6. Doanh thu chưa thực hiện ngắn hạn', 'kind': 'leaf', 'level': 2, 'sign_role': 'liability'},
    {'code': '319', 'name': '7. Phải trả ngắn hạn khác', 'kind': 'leaf', 'level': 2, 'sign_role': 'liability'},
    {'code': '320', 'name': '8. Vay và nợ thuê tài chính ngắn hạn', 'kind': 'leaf', 'level': 2, 'sign_role': 'liability'},
    {'code': '322', 'name': '9. Quỹ khen thưởng, phúc lợi', 'kind': 'leaf', 'level': 2, 'sign_role': 'liability'},
    {'code': '310', 'name': 'I. Nợ ngắn hạn', 'kind': 'calc', 'level': 1,
     'formula': '311 + 313 + 314 + 315 + 316 + 318 + 319 + 320 + 322'},
    {'code': '337', 'name': '1. Phải trả dài hạn khác / ký quỹ', 'kind': 'leaf', 'level': 2, 'sign_role': 'liability'},
    {'code': '338', 'name': '2. Vay và nợ dài hạn / trái phiếu', 'kind': 'leaf', 'level': 2, 'sign_role': 'liability'},
    {'code': '341', 'name': '3. Thuế thu nhập hoãn lại phải trả', 'kind': 'leaf', 'level': 2, 'sign_role': 'liability'},
    {'code': '342', 'name': '4. Dự phòng phải trả dài hạn', 'kind': 'leaf', 'level': 2, 'sign_role': 'liability'},
    {'code': '330', 'name': 'II. Nợ dài hạn', 'kind': 'calc', 'level': 1,
     'formula': '337 + 338 + 341 + 342'},
    {'code': '300', 'name': 'TỔNG CỘNG NỢ PHẢI TRẢ', 'kind': 'calc', 'level': 0,
     'formula': '310 + 330', 'bold': True},

    {'code': 'D', 'name': 'D. VỐN CHỦ SỞ HỮU', 'kind': 'header', 'level': 0},
    {'code': '411', 'name': '1. Vốn góp của chủ sở hữu', 'kind': 'leaf', 'level': 2, 'sign_role': 'equity'},
    {'code': '412', 'name': '2. Chênh lệch đánh giá lại tài sản', 'kind': 'leaf', 'level': 2, 'sign_role': 'equity'},
    {'code': '413', 'name': '3. Chênh lệch tỷ giá hối đoái', 'kind': 'leaf', 'level': 2, 'sign_role': 'equity'},
    {'code': '418', 'name': '4. Các quỹ thuộc vốn chủ sở hữu', 'kind': 'leaf', 'level': 2, 'sign_role': 'equity'},
    {'code': '419', 'name': '5. Cổ phiếu quỹ (*)', 'kind': 'leaf', 'level': 2, 'sign_role': 'asset'},
    {'code': '421', 'name': '6. Lợi nhuận sau thuế chưa phân phối', 'kind': 'leaf', 'level': 2, 'sign_role': 'equity'},
    {'code': '422', 'name': '7. Nguồn vốn đầu tư XDCB', 'kind': 'leaf', 'level': 2, 'sign_role': 'equity'},
    {'code': '410', 'name': 'I. Vốn chủ sở hữu', 'kind': 'calc', 'level': 1,
     'formula': '411 + 412 + 413 + 418 - 419 + 421 + 422'},
    {'code': '400', 'name': 'TỔNG CỘNG VỐN CHỦ SỞ HỮU', 'kind': 'calc', 'level': 0,
     'formula': '410', 'bold': True},
    {'code': '440', 'name': 'TỔNG CỘNG NGUỒN VỐN', 'kind': 'calc', 'level': 0,
     'formula': '300 + 400', 'bold': True, 'highlight': True},
]

B02_INCOME_STATEMENT: list[dict] = [
    {'code': '01', 'name': '1. Doanh thu bán hàng và cung cấp dịch vụ', 'kind': 'leaf', 'level': 1, 'sign_role': 'revenue'},
    {'code': '02', 'name': '2. Các khoản giảm trừ doanh thu', 'kind': 'leaf', 'level': 1, 'sign_role': 'expense'},
    {'code': '10', 'name': '3. Doanh thu thuần về bán hàng và CCDV', 'kind': 'calc', 'level': 0,
     'formula': '01 - 02', 'bold': True},
    {'code': '11', 'name': '4. Giá vốn hàng bán', 'kind': 'leaf', 'level': 1, 'sign_role': 'expense'},
    {'code': '20', 'name': '5. Lợi nhuận gộp về bán hàng và CCDV', 'kind': 'calc', 'level': 0,
     'formula': '10 - 11', 'bold': True},
    {'code': '21', 'name': '6. Doanh thu hoạt động tài chính', 'kind': 'leaf', 'level': 1, 'sign_role': 'revenue'},
    {'code': '22', 'name': '7. Chi phí tài chính', 'kind': 'leaf', 'level': 1, 'sign_role': 'expense'},
    {'code': '25', 'name': '8. Chi phí bán hàng', 'kind': 'leaf', 'level': 1, 'sign_role': 'expense'},
    {'code': '26', 'name': '9. Chi phí quản lý doanh nghiệp', 'kind': 'leaf', 'level': 1, 'sign_role': 'expense'},
    {'code': '30', 'name': '10. Lợi nhuận thuần từ hoạt động kinh doanh', 'kind': 'calc', 'level': 0,
     'formula': '20 + 21 - 22 - 25 - 26', 'bold': True},
    {'code': '31', 'name': '11. Thu nhập khác', 'kind': 'leaf', 'level': 1, 'sign_role': 'revenue'},
    {'code': '32', 'name': '12. Chi phí khác', 'kind': 'leaf', 'level': 1, 'sign_role': 'expense'},
    {'code': '40', 'name': '13. Lợi nhuận khác', 'kind': 'calc', 'level': 0, 'formula': '31 - 32'},
    {'code': '50', 'name': '14. Tổng lợi nhuận kế toán trước thuế', 'kind': 'calc', 'level': 0,
     'formula': '30 + 40', 'bold': True, 'highlight': True},
    {'code': '51', 'name': '15. Chi phí thuế TNDN hiện hành', 'kind': 'leaf', 'level': 1, 'sign_role': 'expense'},
    {'code': '60', 'name': '16. Lợi nhuận sau thuế thu nhập doanh nghiệp', 'kind': 'calc', 'level': 0,
     'formula': '50 - 51', 'bold': True, 'highlight': True},
]

# B03-DN — Lưu chuyển tiền tệ (gián tiếp rút gọn + phân loại từ nhật ký)
# leaf kind đặc biệt: nguồn số liệu do engine gán (cashflow_keys), không map COA.
B03_CASH_FLOW: list[dict] = [
    {'code': 'I', 'name': 'I. LƯU CHUYỂN TIỀN TỪ HOẠT ĐỘNG KINH DOANH', 'kind': 'header', 'level': 0},
    {'code': '01', 'name': '1. Lợi nhuận trước thuế', 'kind': 'leaf', 'level': 1, 'cf_key': 'profit_before_tax'},
    {'code': '02', 'name': '2. Điều chỉnh cho các khoản', 'kind': 'calc', 'level': 1, 'formula': '03 + 04'},
    {'code': '03', 'name': '   - Khấu hao TSCĐ và BĐSĐT', 'kind': 'leaf', 'level': 2, 'cf_key': 'depreciation'},
    {'code': '04', 'name': '   - Các khoản điều chỉnh khác', 'kind': 'leaf', 'level': 2, 'cf_key': 'other_adjustments'},
    {'code': '05', 'name': '3. Tăng/giảm các khoản phải thu', 'kind': 'leaf', 'level': 1, 'cf_key': 'delta_receivables'},
    {'code': '06', 'name': '4. Tăng/giảm hàng tồn kho', 'kind': 'leaf', 'level': 1, 'cf_key': 'delta_inventory'},
    {'code': '07', 'name': '5. Tăng/giảm các khoản phải trả (không kể lãi vay, thuế TNDN)', 'kind': 'leaf', 'level': 1, 'cf_key': 'delta_payables'},
    {'code': '08', 'name': '6. Tăng/giảm chi phí trả trước', 'kind': 'leaf', 'level': 1, 'cf_key': 'delta_prepaid'},
    {'code': '09', 'name': '7. Tiền lãi vay đã trả', 'kind': 'leaf', 'level': 1, 'cf_key': 'interest_paid'},
    {'code': '10', 'name': '8. Thuế thu nhập doanh nghiệp đã nộp', 'kind': 'leaf', 'level': 1, 'cf_key': 'tax_paid'},
    {'code': '11', 'name': '9. Tiền thu khác từ hoạt động kinh doanh', 'kind': 'leaf', 'level': 1, 'cf_key': 'other_operating_in'},
    {'code': '12', 'name': '10. Tiền chi khác cho hoạt động kinh doanh', 'kind': 'leaf', 'level': 1, 'cf_key': 'other_operating_out'},
    {'code': '20', 'name': 'Lưu chuyển tiền thuần từ hoạt động kinh doanh', 'kind': 'calc', 'level': 0,
     'formula': '01 + 02 + 05 + 06 + 07 + 08 + 09 + 10 + 11 + 12', 'bold': True, 'highlight': True},

    {'code': 'II', 'name': 'II. LƯU CHUYỂN TIỀN TỪ HOẠT ĐỘNG ĐẦU TƯ', 'kind': 'header', 'level': 0},
    {'code': '21', 'name': '1. Tiền chi để mua sắm, xây dựng TSCĐ và các tài sản dài hạn khác', 'kind': 'leaf', 'level': 1, 'cf_key': 'investing_out'},
    {'code': '22', 'name': '2. Tiền thu từ thanh lý, nhượng bán TSCĐ và tài sản dài hạn khác', 'kind': 'leaf', 'level': 1, 'cf_key': 'investing_in'},
    {'code': '23', 'name': '3. Tiền chi cho vay, mua các công cụ nợ của đơn vị khác', 'kind': 'leaf', 'level': 1, 'cf_key': 'investing_lend_out'},
    {'code': '24', 'name': '4. Tiền thu hồi cho vay, bán lại các công cụ nợ của đơn vị khác', 'kind': 'leaf', 'level': 1, 'cf_key': 'investing_lend_in'},
    {'code': '25', 'name': '5. Tiền chi đầu tư góp vốn vào đơn vị khác', 'kind': 'leaf', 'level': 1, 'cf_key': 'investing_equity_out'},
    {'code': '26', 'name': '6. Tiền thu hồi đầu tư góp vốn vào đơn vị khác', 'kind': 'leaf', 'level': 1, 'cf_key': 'investing_equity_in'},
    {'code': '27', 'name': '7. Tiền thu lãi cho vay, cổ tức và lợi nhuận được chia', 'kind': 'leaf', 'level': 1, 'cf_key': 'investing_income'},
    {'code': '30', 'name': 'Lưu chuyển tiền thuần từ hoạt động đầu tư', 'kind': 'calc', 'level': 0,
     'formula': '21 + 22 + 23 + 24 + 25 + 26 + 27', 'bold': True, 'highlight': True},

    {'code': 'III', 'name': 'III. LƯU CHUYỂN TIỀN TỪ HOẠT ĐỘNG TÀI CHÍNH', 'kind': 'header', 'level': 0},
    {'code': '31', 'name': '1. Tiền thu từ phát hành cổ phiếu, nhận vốn góp của chủ sở hữu', 'kind': 'leaf', 'level': 1, 'cf_key': 'financing_equity_in'},
    {'code': '32', 'name': '2. Tiền chi trả vốn góp cho các chủ sở hữu, mua lại cổ phiếu', 'kind': 'leaf', 'level': 1, 'cf_key': 'financing_equity_out'},
    {'code': '33', 'name': '3. Tiền thu từ đi vay', 'kind': 'leaf', 'level': 1, 'cf_key': 'financing_borrow_in'},
    {'code': '34', 'name': '4. Tiền chi trả nợ gốc vay', 'kind': 'leaf', 'level': 1, 'cf_key': 'financing_borrow_out'},
    {'code': '35', 'name': '5. Tiền chi trả nợ thuê tài chính', 'kind': 'leaf', 'level': 1, 'cf_key': 'financing_lease_out'},
    {'code': '36', 'name': '6. Cổ tức, lợi nhuận đã trả cho chủ sở hữu', 'kind': 'leaf', 'level': 1, 'cf_key': 'financing_dividend'},
    {'code': '40', 'name': 'Lưu chuyển tiền thuần từ hoạt động tài chính', 'kind': 'calc', 'level': 0,
     'formula': '31 + 32 + 33 + 34 + 35 + 36', 'bold': True, 'highlight': True},

    {'code': '50', 'name': 'Lưu chuyển tiền thuần trong kỳ', 'kind': 'calc', 'level': 0,
     'formula': '20 + 30 + 40', 'bold': True, 'highlight': True},
    {'code': '60', 'name': 'Tiền và tương đương tiền đầu kỳ', 'kind': 'leaf', 'level': 0, 'cf_key': 'cash_opening', 'bold': True},
    {'code': '70', 'name': 'Tiền và tương đương tiền cuối kỳ', 'kind': 'calc', 'level': 0,
     'formula': '60 + 50', 'bold': True, 'highlight': True},
]
