"""Quy tắc định khoản mặc định SME (TT99) — tham chiếu mã trong sme_chart_of_accounts."""
from __future__ import annotations

RULES_SEED_VERSION = 'posting_rules_v6_2026-08-ledger-ops'

# payment_method: CASH | BANK_TRANSFER | CREDIT
# business_type: mã nghiệp vụ nội bộ phần mềm
DEFAULT_POSTING_RULES: list[dict] = [
    # Nhập kho hàng hóa (156)
    {
        'business_type': 'NHAP_KHO_HANG_HOA',
        'payment_method': 'CASH',
        'debit_account_code': '156',
        'credit_account_code': '1111',
        'vat_account_code': '13311',
        'import_tax_credit_account': '3333',
        'is_vat_applicable': 1,
        'description': 'Nhập hàng hóa — trả tiền mặt',
    },
    {
        'business_type': 'NHAP_KHO_HANG_HOA',
        'payment_method': 'BANK_TRANSFER',
        'debit_account_code': '156',
        'credit_account_code': '1121',
        'vat_account_code': '13311',
        'import_tax_credit_account': '3333',
        'is_vat_applicable': 1,
        'description': 'Nhập hàng hóa — chuyển khoản',
    },
    {
        'business_type': 'NHAP_KHO_HANG_HOA',
        'payment_method': 'CREDIT',
        'debit_account_code': '156',
        'credit_account_code': '331',
        'vat_account_code': '13311',
        'import_tax_credit_account': '3333',
        'is_vat_applicable': 1,
        'description': 'Nhập hàng hóa — chưa thanh toán (công nợ NCC)',
    },
    # Nhập kho NVL (152)
    {
        'business_type': 'NHAP_KHO_NVL',
        'payment_method': 'CASH',
        'debit_account_code': '152',
        'credit_account_code': '1111',
        'vat_account_code': '13311',
        'import_tax_credit_account': '3333',
        'is_vat_applicable': 1,
        'description': 'Nhập NVL — trả tiền mặt',
    },
    {
        'business_type': 'NHAP_KHO_NVL',
        'payment_method': 'BANK_TRANSFER',
        'debit_account_code': '152',
        'credit_account_code': '1121',
        'vat_account_code': '13311',
        'import_tax_credit_account': '3333',
        'is_vat_applicable': 1,
        'description': 'Nhập NVL — chuyển khoản',
    },
    {
        'business_type': 'NHAP_KHO_NVL',
        'payment_method': 'CREDIT',
        'debit_account_code': '152',
        'credit_account_code': '331',
        'vat_account_code': '13311',
        'import_tax_credit_account': '3333',
        'is_vat_applicable': 1,
        'description': 'Nhập NVL — chưa thanh toán',
    },
    # Mua dịch vụ (642)
    {
        'business_type': 'MUA_DICH_VU',
        'payment_method': 'CASH',
        'debit_account_code': '642',
        'credit_account_code': '1111',
        'vat_account_code': '13311',
        'import_tax_credit_account': None,
        'is_vat_applicable': 1,
        'description': 'Mua dịch vụ — trả tiền mặt',
    },
    {
        'business_type': 'MUA_DICH_VU',
        'payment_method': 'BANK_TRANSFER',
        'debit_account_code': '642',
        'credit_account_code': '1121',
        'vat_account_code': '13311',
        'import_tax_credit_account': None,
        'is_vat_applicable': 1,
        'description': 'Mua dịch vụ — chuyển khoản',
    },
    {
        'business_type': 'MUA_DICH_VU',
        'payment_method': 'CREDIT',
        'debit_account_code': '642',
        'credit_account_code': '331',
        'vat_account_code': '13311',
        'import_tax_credit_account': None,
        'is_vat_applicable': 1,
        'description': 'Mua dịch vụ — công nợ NCC',
    },
    # Mua TSCĐ hữu hình (2112 mặc định — máy móc thiết bị)
    {
        'business_type': 'MUA_TSCD',
        'payment_method': 'CASH',
        'debit_account_code': '2112',
        'credit_account_code': '1111',
        'vat_account_code': '13311',
        'import_tax_credit_account': '3333',
        'is_vat_applicable': 1,
        'description': 'Mua TSCĐ — trả tiền mặt',
    },
    {
        'business_type': 'MUA_TSCD',
        'payment_method': 'BANK_TRANSFER',
        'debit_account_code': '2112',
        'credit_account_code': '1121',
        'vat_account_code': '13311',
        'import_tax_credit_account': '3333',
        'is_vat_applicable': 1,
        'description': 'Mua TSCĐ — chuyển khoản',
    },
    {
        'business_type': 'MUA_TSCD',
        'payment_method': 'CREDIT',
        'debit_account_code': '2112',
        'credit_account_code': '331',
        'vat_account_code': '13311',
        'import_tax_credit_account': '3333',
        'is_vat_applicable': 1,
        'description': 'Mua TSCĐ — công nợ NCC',
    },
    # Mua CCDC (153)
    {
        'business_type': 'MUA_CCDC',
        'payment_method': 'CASH',
        'debit_account_code': '153',
        'credit_account_code': '1111',
        'vat_account_code': '13311',
        'import_tax_credit_account': '3333',
        'is_vat_applicable': 1,
        'description': 'Mua CCDC — trả tiền mặt',
    },
    {
        'business_type': 'MUA_CCDC',
        'payment_method': 'BANK_TRANSFER',
        'debit_account_code': '153',
        'credit_account_code': '1121',
        'vat_account_code': '13311',
        'import_tax_credit_account': '3333',
        'is_vat_applicable': 1,
        'description': 'Mua CCDC — chuyển khoản',
    },
    {
        'business_type': 'MUA_CCDC',
        'payment_method': 'CREDIT',
        'debit_account_code': '153',
        'credit_account_code': '331',
        'vat_account_code': '13311',
        'import_tax_credit_account': '3333',
        'is_vat_applicable': 1,
        'description': 'Mua CCDC — công nợ NCC',
    },
    # Khấu hao / phân bổ (tự động theo kỳ)
    {
        'business_type': 'KHAU_HAO_TSCD',
        'payment_method': 'INTERNAL',
        'debit_account_code': '642',
        'credit_account_code': '2141',
        'vat_account_code': None,
        'import_tax_credit_account': None,
        'is_vat_applicable': 0,
        'description': 'Khấu hao TSCĐ hữu hình (Nợ 642 / Có 2141)',
    },
    {
        'business_type': 'PHAN_BO_CCDC',
        'payment_method': 'INTERNAL',
        'debit_account_code': '642',
        'credit_account_code': '153',
        'vat_account_code': None,
        'import_tax_credit_account': None,
        'is_vat_applicable': 0,
        'description': 'Phân bổ CCDC vào chi phí (Nợ 642 / Có 153)',
    },
    # Bán hàng
    {
        'business_type': 'BAN_HANG_TM',
        'payment_method': 'CASH',
        'debit_account_code': '1111',
        'credit_account_code': '5111',
        'vat_account_code': '33311',
        'import_tax_credit_account': None,
        'is_vat_applicable': 1,
        'description': 'Bán hàng thu tiền mặt',
    },
    {
        'business_type': 'BAN_HANG_CK',
        'payment_method': 'BANK_TRANSFER',
        'debit_account_code': '1121',
        'credit_account_code': '5111',
        'vat_account_code': '33311',
        'import_tax_credit_account': None,
        'is_vat_applicable': 1,
        'description': 'Bán hàng chuyển khoản',
    },
    {
        'business_type': 'BAN_HANG_CONG_NO',
        'payment_method': 'CREDIT',
        'debit_account_code': '131',
        'credit_account_code': '5111',
        'vat_account_code': '33311',
        'import_tax_credit_account': None,
        'is_vat_applicable': 1,
        'description': 'Bán hàng công nợ',
    },
    # Phiếu thu / chi thủ công (01-TT / 02-TT)
    {
        'business_type': 'THU_TIEN',
        'payment_method': 'CASH',
        'debit_account_code': '1111',
        'credit_account_code': '131',
        'vat_account_code': None,
        'import_tax_credit_account': None,
        'is_vat_applicable': 0,
        'description': 'Phiếu thu tiền mặt (01-TT)',
    },
    {
        'business_type': 'THU_TIEN',
        'payment_method': 'BANK_TRANSFER',
        'debit_account_code': '1121',
        'credit_account_code': '131',
        'vat_account_code': None,
        'import_tax_credit_account': None,
        'is_vat_applicable': 0,
        'description': 'Phiếu thu chuyển khoản (01-TT)',
    },
    {
        'business_type': 'CHI_TIEN',
        'payment_method': 'CASH',
        'debit_account_code': '331',
        'credit_account_code': '1111',
        'vat_account_code': None,
        'import_tax_credit_account': None,
        'is_vat_applicable': 0,
        'description': 'Phiếu chi tiền mặt (02-TT)',
    },
    {
        'business_type': 'CHI_TIEN',
        'payment_method': 'BANK_TRANSFER',
        'debit_account_code': '331',
        'credit_account_code': '1121',
        'vat_account_code': None,
        'import_tax_credit_account': None,
        'is_vat_applicable': 0,
        'description': 'Phiếu chi chuyển khoản (02-TT)',
    },
    # Trích lương / trả lương
    {
        'business_type': 'TRICH_LUONG',
        'payment_method': 'CREDIT',
        'debit_account_code': '642',
        'credit_account_code': '3341',
        'vat_account_code': None,
        'import_tax_credit_account': None,
        'is_vat_applicable': 0,
        'description': 'Trích lương phải trả NLĐ',
    },
    {
        'business_type': 'SAN_XUAT_TP',
        'payment_method': 'CREDIT',
        'debit_account_code': '155',
        'credit_account_code': '152',
        'vat_account_code': None,
        'import_tax_credit_account': None,
        'is_vat_applicable': 0,
        'description': 'Sản xuất — nhập thành phẩm / xuất NVL',
    },
    # Tiền đang chuyển / giảm trừ DT / KPCĐ / dự phòng / thuê TC
    {
        'business_type': 'NOP_NGAN_HANG',
        'payment_method': 'CASH',
        'debit_account_code': '1131',
        'credit_account_code': '1111',
        'vat_account_code': None,
        'import_tax_credit_account': None,
        'is_vat_applicable': 0,
        'description': 'Nộp tiền mặt vào NH — tiền đang chuyển',
    },
    {
        'business_type': 'TAT_TOAN_113',
        'payment_method': 'BANK_TRANSFER',
        'debit_account_code': '1121',
        'credit_account_code': '1131',
        'vat_account_code': None,
        'import_tax_credit_account': None,
        'is_vat_applicable': 0,
        'description': 'Tất toán tiền đang chuyển vào TGNH',
    },
    {
        'business_type': 'TRA_HANG_BAN',
        'payment_method': 'CASH',
        'debit_account_code': '5212',
        'credit_account_code': '1111',
        'vat_account_code': '33311',
        'import_tax_credit_account': None,
        'is_vat_applicable': 1,
        'description': 'Hàng bán bị trả lại',
    },
    {
        'business_type': 'GIAM_TRU_DOANH_THU',
        'payment_method': 'CREDIT',
        'debit_account_code': '5211',
        'credit_account_code': '131',
        'vat_account_code': '33311',
        'import_tax_credit_account': None,
        'is_vat_applicable': 1,
        'description': 'Chiết khấu / giảm giá hàng bán',
    },
    {
        'business_type': 'TRICH_KPCD',
        'payment_method': 'CREDIT',
        'debit_account_code': '642',
        'credit_account_code': '3382',
        'vat_account_code': None,
        'import_tax_credit_account': None,
        'is_vat_applicable': 0,
        'description': 'Trích kinh phí công đoàn 2% quỹ lương',
    },
    {
        'business_type': 'TRICH_DU_PHONG',
        'payment_method': 'INTERNAL',
        'debit_account_code': '642',
        'credit_account_code': '2293',
        'vat_account_code': None,
        'import_tax_credit_account': None,
        'is_vat_applicable': 0,
        'description': 'Trích dự phòng phải thu khó đòi',
    },
    {
        'business_type': 'THUE_TAI_CHINH',
        'payment_method': 'CREDIT',
        'debit_account_code': '212',
        'credit_account_code': '3412',
        'vat_account_code': None,
        'import_tax_credit_account': None,
        'is_vat_applicable': 0,
        'description': 'Nhận TSCĐ thuê tài chính',
    },
    {
        'business_type': 'PHAN_PHOI_LN',
        'payment_method': 'INTERNAL',
        'debit_account_code': '4212',
        'credit_account_code': '418',
        'vat_account_code': None,
        'import_tax_credit_account': None,
        'is_vat_applicable': 0,
        'description': 'Phân phối lợi nhuận sau thuế',
    },
]
